[package]
name = "rugl"
version = "0.1.0"
authors = ["spelufo <santiagopelufo@gmail.com>"]
edition = "2018"


[dependencies]
glfw = "0.37"
gl = "0.14"
image = "0.23"
freetype-rs = "0.24"
notify = "5.0.0-pre.2"